### PR TITLE
Add EGA (encrypt and) submit TES task

### PR DESCRIPTION
**Pull request by brainstorm**
Will probably need two tasks that coordinate (over GDS?). Otherwise I could put aspera+egacrypt together in a single docker container to simplify orchestration...

/cc @reisingerf

### CODE REVIEW

**Comment by alexiswl** [comment]
We can string to tasks together in an ISL workflow

**Comment by alexiswl** [comment]
Docker images will need to be public though, we can parse through secrets into the containers

**Comment by brainstorm** [comment]
Superseeded by #109

**Comment by alexiswl** [comment]
Hmm. getting the error:

```
2024-05-28T02:39:58.461398437Z stderr F ascp: no remote host specified
2024-05-28T02:39:58.461423353Z stderr F Startup failed, exit
```

Which likely means the scp syntax ` ${USERNAME}:${SECURE_PASSWORD}@${HOSTNAME}:${EGA_DEST_PATH}` won't do.

**Pull request closed without merging**
